### PR TITLE
Remove retry command from dispense on puloon

### PR DESCRIPTION
**Pull request by RafaelTaranto**

### CODE REVIEW

**Comment by RafaelTaranto** [comment]
[Remove retry command from puloon code](https://trello.com/c/W7sfRJ2E/804-remove-retry-command-from-puloon-code)

**Comment by joshmh** [comment]
I'm thinking maybe we should just completely remove retry. With retry in here, we could send a new command while we're still retrying the old command which will confuse the Puloon even more. @RafaelTaranto what do you think?

**Comment by RafaelTaranto** [comment]
That was my first idea but after going through the cards of the original
commit looked like the retry did fix something.

But it does feel like we should favor a more stable puloon code, yeah.

**Comment by joshmh** [comment]
Ok, I'll merge for now and we can revisit later.

**Pull request merged**
