### PR TITLE
Make embedded svg hide cursor

### PR DESCRIPTION
**Pull request by RafaelTaranto**

### CODE REVIEW

**Comment by RafaelTaranto** [comment]
[Tapping on animations allows mouse pointer to show, disappearing shortly afterwards](https://trello.com/c/Ok7yjLkS/211-tapping-on-animations-allows-mouse-pointer-to-show-disappearing-shortly-afterwards)

**Comment by joshmh** [comment]
@RafaelTaranto Is it possible to style this with just a single CSS descriptor in the main file instead of needing to add that descriptor in every SVG file? Or is it possible to hide the cursor at the OS level just for the browser window?

**Comment by RafaelTaranto** [comment]
> Is it possible to style this with just a single CSS descriptor in the main file instead of needing to add that descriptor in every SVG file?

Not really, we're using Object on the animated svgs because of the older chromium version and that starts a new document.

> Or is it possible to hide the cursor at the OS level just for the browser window?

I'll do some research into this.

**Comment by joshmh** [comment]
Ok, let's keep it like this.

**Pull request merged**
